[package]
name = "aircode-client"
version = "0.1.0"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]

[dependencies]
json = "0.11"
promptly = "0.1.5"
reqwest = "0.9"
rustyline = "1.0.0"
scraper = "0.7"