[package]
name = "aircode-client"
version = "0.1.0"
authors = ["David Harvey-Macaulay <alteous@outlook.com>"]
edition = "2018"

[dependencies]
json = "0.11"
marksman_escape = "0.1"
notify = "4.0"
promptly = "0.1"
reqwest = "0.9"
rustyline = "1.0"
scraper = "0.10"
structopt = "0.2"